START TRANSACTION

DROP DATABASE IF EXISTS `video_tutorials`
CREATE DATABASE `video_tutorials`

DROP TABLE IF EXISTS `video`
CREATE TABLE `video` (
  `id` INT AUTO_INCREMENT,
  `author` VARCHAR(64),
  `title` VARCHAR(128),
  `parts` INT UNSIGNED,
  `description` MEDIUMTEXT,
  PRIMARY KEY (id)
) ENGINE=MyISAM

COMMIT
